// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetFilesFileIDParams creates a new GetFilesFileIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetFilesFileIDParams() *GetFilesFileIDParams {
	return &GetFilesFileIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetFilesFileIDParamsWithTimeout creates a new GetFilesFileIDParams object
// with the ability to set a timeout on a request.
func NewGetFilesFileIDParamsWithTimeout(timeout time.Duration) *GetFilesFileIDParams {
	return &GetFilesFileIDParams{
		timeout: timeout,
	}
}

// NewGetFilesFileIDParamsWithContext creates a new GetFilesFileIDParams object
// with the ability to set a context for a request.
func NewGetFilesFileIDParamsWithContext(ctx context.Context) *GetFilesFileIDParams {
	return &GetFilesFileIDParams{
		Context: ctx,
	}
}

// NewGetFilesFileIDParamsWithHTTPClient creates a new GetFilesFileIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetFilesFileIDParamsWithHTTPClient(client *http.Client) *GetFilesFileIDParams {
	return &GetFilesFileIDParams{
		HTTPClient: client,
	}
}

/* GetFilesFileIDParams contains all the parameters to send to the API endpoint
   for the get files file ID operation.

   Typically these are written to a http.Request.
*/
type GetFilesFileIDParams struct {

	/* FileID.

	   File identification

	   Format: int32
	*/
	FileID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get files file ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFilesFileIDParams) WithDefaults() *GetFilesFileIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get files file ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFilesFileIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get files file ID params
func (o *GetFilesFileIDParams) WithTimeout(timeout time.Duration) *GetFilesFileIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get files file ID params
func (o *GetFilesFileIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get files file ID params
func (o *GetFilesFileIDParams) WithContext(ctx context.Context) *GetFilesFileIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get files file ID params
func (o *GetFilesFileIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get files file ID params
func (o *GetFilesFileIDParams) WithHTTPClient(client *http.Client) *GetFilesFileIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get files file ID params
func (o *GetFilesFileIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFileID adds the fileID to the get files file ID params
func (o *GetFilesFileIDParams) WithFileID(fileID int32) *GetFilesFileIDParams {
	o.SetFileID(fileID)
	return o
}

// SetFileID adds the fileId to the get files file ID params
func (o *GetFilesFileIDParams) SetFileID(fileID int32) {
	o.FileID = fileID
}

// WriteToRequest writes these params to a swagger request
func (o *GetFilesFileIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param file-id
	if err := r.SetPathParam("file-id", swag.FormatInt32(o.FileID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
