// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostFilesParams creates a new PostFilesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostFilesParams() *PostFilesParams {
	return &PostFilesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostFilesParamsWithTimeout creates a new PostFilesParams object
// with the ability to set a timeout on a request.
func NewPostFilesParamsWithTimeout(timeout time.Duration) *PostFilesParams {
	return &PostFilesParams{
		timeout: timeout,
	}
}

// NewPostFilesParamsWithContext creates a new PostFilesParams object
// with the ability to set a context for a request.
func NewPostFilesParamsWithContext(ctx context.Context) *PostFilesParams {
	return &PostFilesParams{
		Context: ctx,
	}
}

// NewPostFilesParamsWithHTTPClient creates a new PostFilesParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostFilesParamsWithHTTPClient(client *http.Client) *PostFilesParams {
	return &PostFilesParams{
		HTTPClient: client,
	}
}

/*
PostFilesParams contains all the parameters to send to the API endpoint

	for the post files operation.

	Typically these are written to a http.Request.
*/
type PostFilesParams struct {

	/* FileContent.

	   The raw file

	   Format: byte
	*/
	FileContent strfmt.Base64

	/* FileName.

	   Name of the file
	*/
	FileName string

	/* FleetID.

	   Fleet identification
	*/
	FleetID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post files params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostFilesParams) WithDefaults() *PostFilesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post files params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostFilesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post files params
func (o *PostFilesParams) WithTimeout(timeout time.Duration) *PostFilesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post files params
func (o *PostFilesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post files params
func (o *PostFilesParams) WithContext(ctx context.Context) *PostFilesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post files params
func (o *PostFilesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post files params
func (o *PostFilesParams) WithHTTPClient(client *http.Client) *PostFilesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post files params
func (o *PostFilesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFileContent adds the fileContent to the post files params
func (o *PostFilesParams) WithFileContent(fileContent strfmt.Base64) *PostFilesParams {
	o.SetFileContent(fileContent)
	return o
}

// SetFileContent adds the fileContent to the post files params
func (o *PostFilesParams) SetFileContent(fileContent strfmt.Base64) {
	o.FileContent = fileContent
}

// WithFileName adds the fileName to the post files params
func (o *PostFilesParams) WithFileName(fileName string) *PostFilesParams {
	o.SetFileName(fileName)
	return o
}

// SetFileName adds the fileName to the post files params
func (o *PostFilesParams) SetFileName(fileName string) {
	o.FileName = fileName
}

// WithFleetID adds the fleetID to the post files params
func (o *PostFilesParams) WithFleetID(fleetID string) *PostFilesParams {
	o.SetFleetID(fleetID)
	return o
}

// SetFleetID adds the fleetId to the post files params
func (o *PostFilesParams) SetFleetID(fleetID string) {
	o.FleetID = fleetID
}

// WriteToRequest writes these params to a swagger request
func (o *PostFilesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.FileContent); err != nil {
		return err
	}

	// query param file_name
	qrFileName := o.FileName
	qFileName := qrFileName
	if qFileName != "" {

		if err := r.SetQueryParam("file_name", qFileName); err != nil {
			return err
		}
	}

	// query param fleet_id
	qrFleetID := o.FleetID
	qFleetID := qrFleetID
	if qFleetID != "" {

		if err := r.SetQueryParam("fleet_id", qFleetID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
